version: "3"

networks:
  traefik_traefik-network:
    external: true

services:
  recipes:
    image: recipes:latest
    container_name: recipes
    build: .
    networks:
      - traefik_traefik-network
    labels:
      - traefik.http.routers.recipes.rule=Host(`recipes.whitney.rip`)
      - traefik.http.routers.recipes.tls=true
      - traefik.http.routers.recipes.tls.certresolver=lets-encrypt
      - traefik.http.services.recipes.loadbalancer.server.port=3000
      - traefik.port=3001

