networks:
  traefik:
    external: true

services:
  recipes:
    image: recipes:latest
    container_name: recipes
    restart: unless-stopped
    build: .
    networks:
      - traefik
    labels:
      - traefik.http.routers.recipes.rule=Host(`recipes.whitney.rip`)
      - traefik.http.routers.recipes.tls=true
      - traefik.http.routers.recipes.tls.certresolver=lets-encrypt
      - traefik.http.services.recipes.loadbalancer.server.port=3000
      - traefik.port=3001

